title:            pedrolamas.com
description:      Windows Development
url:              https://www.pedrolamas.com
lang:             en-US
logo:             /logo.jpg
feedurl:          http://feeds.feedburner.com/pedrolamascom

author:
  name:           Pedro Lamas
  email:          pedrolamas@gmail.com
  url:            https://www.pedrolamas.com

twitter:
  username:       pedrolamas

facebook:
  app_id:         401681359922124
  publisher:      150703221746608
  admins:         1049758397

github:
  username:       pedrolamas

social:
  name: Pedro Lamas
  links:
    - https://twitter.com/pedrolamas
    - https://www.facebook.com/pedrolamas
    - https://www.linkedin.com/in/pedrolamas
    - https://github.com/pedrolamas

google_analytics: UA-1376452-1
disqus_shortname: pedrolamas-com
addthis_profile:  ra-58b55b8d7a40cd51

permalink:        /:year/:month/:day/:title/
paginate:         8
paginate_path:    /page/:num/

collections:
  categories:
    output:       true
    permalink:    /category/:title/

defaults:
  - scope:
      path:       ""
      type:       categories
    values:
      layout:     archive

gems:
  - jekyll-redirect-from
  - jekyll-github-metadata
  - jekyll-feed
  - jekyll-sitemap
