[build]
  command = "jekyll build"
  publish = "_site/"
  
[build.environment]
  JEKYLL_ENV = "production"
  PAGES_REPO_NWO = "PedroLamas/pedrolamas.com"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Feature-Policy = "accelerometer 'none'; autoplay 'none'; ambient-light-sensor 'none'; camera 'none'; geolocation 'none'; gyroscope 'none'; magnetometer 'none'; microphone 'none'; midi 'none'; payment 'none'; usb 'none'"
    X-Content-Type-Options = "nosniff"