version: 1
update_configs:
  - package_manager: 'javascript'
    directory: '/'
    update_schedule: 'daily'
    target_branch: 'dependabot'
    automerged_updates:
      - match:
          dependency_type: 'all'
          update_type: 'semver:minor'
    commit_message:
      prefix: '[skip netlify]'
